highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://www.codemilan.com
author: Milan Rawal

# for a normal use at the base of the server change it to "/"
baseurl: /
title: Milan Rawal's Resume
name: Milan Rawal
email: mrawal47@gmail.com
email_full: mailto:mrawal47@gmail.com
website: blog.codemilan.com
website_full: https://blog.codemilan.com
github: codemilan
twitter: codemeelan
tel: +97 9860000367
tel_full: tel:+97 9860000367
google_maps: 'https://www.google.co.np/maps/place/44617+Sahayoginagar+Mahadevsthan,+Koteshwor,+Kathmandu+City+44617'
address:
  street: Sahayoginagar, Mahadevsthan, Koteshwor
  postcode: 44617
  city: Kathmandu
  country: Nepal
google_analytics: #UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
